# Generated by Django 4.0.5 on 2022-06-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField(null=True)),
                ('still_active', models.BooleanField(default=True)),
                ('genre', models.CharField(choices=[('-1', 'not defined'), ('0', 'rock'), ('1', 'metal'), ('2', 'pop'), ('3', 'hip-hop'), ('4', 'electronic'), ('5', 'reggae'), ('6', 'other')], default='-1', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=64, null=True)),
            ],
        ),
    ]
